### Login as a gallery
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "gallery@example.com",
  "password": "Password@1234",
  "userRole": "gallery"
}

> {%
  client.global.set("auth_token", response.body.token.accessToken);
%}

### Adding a new artist to the gallery
POST http://localhost:3000/api/v1/gallery/add-artist
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "firstName": "Artist1",
  "lastName": "Art",
  "bio": "Contemporary mixed-media artist based in Nantes.",
  "portfolioUrl": "https://johndoe.art",
  "nationality": "French",
  "createUserDto": {
    "email": "john.doe@example.fr",
    "password": "Password@1234!",
    "userRole": "artiste"
  }
}