### Login as an admin
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password@1234",
  "userRole": "admin"
}

> {%
  client.global.set("auth_token", response.body.token.accessToken);
%}

### Admin Gallery validation protected route
GET http://localhost:3000/api/v1/admin/validate-gallery-account?galleryId=cfb42b23-7e73-422f-bdb4-12be439559f9
Authorization: Bearer {{auth_token}}
