### Login and capture token
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "gallery@example.com",
  "password": "Password@1234",
  "userRole": "gallery"
}

> {%
  client.global.set("auth_token", response.body.accessToken);
%}