### 1. Login as an artist with artworks
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "a7001@t.co",
  "password": "Password1234!",
  "userRole": "artiste"
}

> {%
  client.global.set("artistAccessToken", response.body.data.token.accessToken);
%}

### 2. Get all artWorks
GET http://localhost:3000/api/v1/artists/art-works
Authorization: Bearer {{artistAccessToken}}



